### ISSUE TITLE
CI needed

### ISSUE THREAD

**Issue by JohanEngelen** [dlang-community/mecca#5]
The TravisCI yml file is already there, so needs registering on TravisCI side and then a dub test (or something along those lines).

**Comment by idanarye** [comment]
We are already running UTs on Travis: https://travis-ci.org/weka-io/mecca

**Comment by JohanEngelen** [comment]
Ah, excellent!
(didn't see it integrated with PRs ?)

**Comment by idanarye** [comment]
* PR #1 - which added `.travis.yaml` - was merged on the 8th of May.
* The only other PR (#3) was created and last modified on the 10th.
* We dragged the process a bit, so Mecca was only activated on TravisCI on the 16th.

So, while `.travis.yaml` was in the repo when PR #3 was created - Mecca was still not activated in TravisCI, and that's why TravisCI did not run it.
